# Generated by Django 4.1 on 2023-01-09 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0002_remove_item_orders_item_created_at_order_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.item"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="organisation",
            name="organisation_items",
            field=models.ManyToManyField(
                through="orders.OrganisationItem", to="orders.item"
            ),
        ),
        migrations.CreateModel(
            name="UserExtended",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="organisationitem",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders.organisation"
            ),
        ),
    ]
