# Generated by Django 4.1 on 2023-01-10 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_organisationitem_organisation_organisation_items_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="county",
            field=models.CharField(default="d", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="first_line",
            field=models.CharField(default="d", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="postcode",
            field=models.CharField(default="d", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="second_line",
            field=models.CharField(default="d", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="street_number",
            field=models.CharField(default="d", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organisationtype",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.location",
            ),
        ),
        migrations.AddField(
            model_name="userextended",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.location",
            ),
        ),
        migrations.AddField(
            model_name="userextended",
            name="phone",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="userextended",
            name="user_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="orders.usertype",
            ),
        ),
    ]
