# Generated by Django 4.1 on 2023-01-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_location_county_location_first_line_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="county",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="location",
            name="first_line",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="location",
            name="second_line",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="location",
            name="street_number",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
