# Generated by Django 4.1 on 2023-01-10 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_remove_organisationtype_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="orders",
            new_name="items",
        ),
    ]
