# Generated by Django 4.1 on 2023-01-15 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_item_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="operational_hub",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operational_hub",
                to="orders.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner",
                to="orders.organisation",
            ),
        ),
    ]
