# Generated by Django 4.1 on 2023-01-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_order_operational_hub_alter_order_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="linked_organisations",
            field=models.ManyToManyField(blank=True, to="orders.organisation"),
        ),
    ]
