# Generated by Django 4.1 on 2023-01-15 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_organisation_linked_organisations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="operational_hub",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operational_hub",
                to="orders.organisation",
            ),
        ),
    ]
