# Generated by Django 4.1.5 on 2023-01-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
